### ISSUE TITLE
[SIOP] Consider revising identity wallet term

### ISSUE THREAD

**Issue by OR13** [decentralized-identity/papers#11]
SIOP is for getting an `id_token` that is linked to a DID. While many will want to store the DID keys in a wallet, from a protocol perspective, thats not relevant, the keys used to prove control of a DID can be stored anywhere, and the ability to produce a valid challenge + response JWTs is the only thing that matters.

It might be worth a short paragraph to highlight this, since technically I can use SIOP from a shell script, there is no requirement to use QRCodes or Mobile Wallets, those are UX.

HTTP is a requirement however.

**Comment by awoie** [comment]
I will replace all occurrences of Identity Wallet with SIOP and I will explain that an SIOP could be any of the following elements in this **non-exhaustive** list:
- Identity Wallet App
- Browser Plugin
- Even a Shell Script
