### ISSUE TITLE
[SIOP] response_mode=query must not be used

### ISSUE THREAD

**Issue by selfissued** [decentralized-identity/papers#24]
The spec currently says that "SIOP implementing the DID AuthN specification MAY set the response_mode to query, or form_post."  This violates the requirement at https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#id_token that "the query encoding MUST NOT be used".  This is a security issue.

It's ok to allow fragment (the default) or form_post, but not query.

**Comment by selfissued** [comment]
Also, delete "or query string" from "If an attacker can cause the <SIOP Response> to be sent a URI under his control, he will directly get access to the fragment or query string carrying the id_token."

**Comment by awoie** [comment]
Thank you. If it breaks the existing spec, then we will remove the option to allow `query`.
