### ISSUE TITLE
[SIOP] did_comm claim not defined

### ISSUE THREAD

**Issue by selfissued** [decentralized-identity/papers#25]
The spec uses the "did_comm" claim in an example and says that it registers it, but the spec does not define it.

**Comment by selfissued** [comment]
Also, I thought that we'd decided to carry the DID in a "did" claim.  The example puts the DID value in a "did" parameter of the "did_comm" claim.  The example also contains a "did_doc" value without saying what this is, when it would be included, and what the validation rules for it are.

**Comment by awoie** [comment]
Thank you for calling that out. We will address the issue by using a `did` and an optional `did_doc` claim. The `did_doc` is needed for some vendors, e.g., for those who implement a did:peer approach.
