### ISSUE TITLE
Encrypting base64url encoded JWTs?

### ISSUE THREAD

**Issue by coder5876** [decentralized-identity/papers#40]
When encrypting a message using JWE where the message is a JWT with header and signature, should we use the base64url encoding of the JWT as the message to encrypt, or use the regular ASCII encoding?

**Comment by tplooker** [comment]
What you are describing I believe is a "nested JWT" (e.g JWS wrapped by a JWE), for this to be valid the inner JWS must be expressed in JWS compact serialisation (base64url safe period delimited form) as that is the only form of JWS that is valid in the JWT specification. The outer JWE must also be expressed in JWE compact serialization.

**Comment by coder5876** [comment]
@tplooker Ok great, thanks! That answers my question!

**Comment by tplooker** [comment]
Cool! @christianlundkvist @awoie shall we close this one then or do we need to amend the specification text to make this clearer?

**Comment by awoie** [comment]
Yes, we can close that issue.
