### ISSUE TITLE
[SIOP] Define what happens in case iss is not https://self-issued.me

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/papers#8]
If `iss` contains a different value than `https://self-issued.me`, then the `id_token` IS NOT an SIOP `id_token` anymore. Instead it MUST be validated according to the rules as defined in [ID Token Validation](https://openid.net/specs/openid-connect-core-1_0.html#IDTokenValidation). We have to check with the OIDC people whether this is applicable.

**Comment by selfissued** [comment]
Per https://openid.net/specs/openid-connect-core-1_0.html#SelfIssuedResponse, the "iss" value in a self-issued ID Token must be "https://self-issued.me".  The self-issued response must be rejected if it is not.

**Comment by awoie** [comment]
Thank you. We can close that issue.
