### ISSUE TITLE
[SIOP] Use sub instead of did

### ISSUE THREAD

**Issue by awoie** [decentralized-identity/papers#9]
The underlying SIOP specification mandates that the `sub` is the sha256 hash of the `sub_jwk`. We should ask the OIDF folks if this can be changed, otherwise we will provide language to the spec that makes the recommendation to use `did` instead of `sub` to identify the SIOP/ user as follows:

> RPs implementing the DID AuthN profile MUST use the `did` instead of the `sub` to identify the SIOP/ user.

**Comment by selfissued** [comment]
This cannot be changed, as OpenID Connect core is a final specification and this would be a breaking change.  Indeed, the subject of the ID Token is the key used for the authentication, so the spec is also correct in the DID Auth case.  The DID is communicated in the "did" claim in this case.

**Comment by awoie** [comment]
Yes, I thought that would be an issue. I believe communicating the DID in the `did` claim is acceptable. I will close this issue.
